#!/usr/bin/env bash

function main(){
    if [ ! $# -eq 2 ]; then
        usage
        exit 1
    fi
    url="$1"
    filename="$2"
    if echo $url | grep -E '^https?://drive.google.com/' > /dev/null; then
        fid=$(get_fid $url)
        if [ -z "$fid" ]; then
            echo "Can't get File id."
            echo "Will be exit..."
            exit 1
        fi
        echo "File id is: $fid"
    else
        echo "Invalid URL"
        echo "Will be exit..."
        exit 1
    fi
    cookie=$(mktemp /tmp/cookie.XXXXXX)
    curl ---silent sc $cookie "https://drive.google.com/uc?export=download&id=$fid" > /dev/null
    echo "Getting code..."
    CODE="$(awk '/_warning_/ {print $NF}' ${cookie})"
    echo "Done"
    echo "Download file..."
    curl -Lb $cookie  -o $filename\
         "https://drive.google.com/uc?export=download&confirm=${CODE}&id=$fid"
    echo "Done"
}

function usage(){
    echo "Overview: Download Google Drive's file from url."
    echo "Usage:"
    echo "gdl URL FILE_NAME"
    echo "  URL  			URL that the file is in"
    echo "  FILE_NAME file name that you want to save"
}

function get_fid(){
    url=$1
    if echo $url | grep -E '^.+?\.com/(uc|open)\?'; then
        fid=$(echo $url | sed -E 's/.*id=([^&]+)[&|$].*/\1/')
    else
        fid=$(echo $url | sed -E 's!^.+?\.com/(file/d|drive/u/[0-9]/folders)/([^/]+)(/view)?!\2!')
    fi
    echo $fid
}

function get_fn(){
    fid=$1
    url="https://drive.google.com/uc?id=$fid"
    filename=$(curl --silent $url | grep "uc-name-size" | sed -E 's!.+<span class="uc-name-size"><a href="[^"]+">([^<]+)</a>.+!\1!')
    echo $filename
}

main $@
